"""add nearby_amenities table

Revision ID: 2b3e2282a918
Revises: 6b4e4b04943e
Create Date: 2026-09-10 14:50:36.398624

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b3e2282a918"
down_revision: str | Sequence[str] | None = "6b4e4b04943e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nearby_amenities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("osm_element_type", sa.String(length=10), nullable=False),
        sa.Column("osm_element_id", sa.BigInteger(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "route_id", "osm_element_type", "osm_element_id", name="uq_nearby_amenities_route_osm_element"
        ),
    )
    # GeoAlchemy2 auto-creates the GiST spatial index on the geometry column
    # at table-creation time (same as points_of_interest's migration) —
    # the autogenerate template's own op.create_index(...) call for it is
    # a duplicate and collides with a "relation already exists" error.
    op.create_index(op.f("ix_nearby_amenities_route_id"), "nearby_amenities", ["route_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_nearby_amenities_route_id"), table_name="nearby_amenities")
    op.drop_table("nearby_amenities")
    # ### end Alembic commands ###
