"""add_route_stats_columns

Revision ID: 300e10b13ea8
Revises: baa412572b68
Create Date: 2026-08-26 10:49:59.252121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300e10b13ea8'
down_revision: Union[str, Sequence[str], None] = 'baa412572b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('routes', sa.Column('elevation_gain_m', sa.Float(), nullable=True))
    op.add_column('routes', sa.Column('elevation_loss_m', sa.Float(), nullable=True))
    op.add_column('routes', sa.Column('duration_minutes', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'duration_minutes')
    op.drop_column('routes', 'elevation_loss_m')
    op.drop_column('routes', 'elevation_gain_m')
    op.drop_column('routes', 'distance_km')
    # ### end Alembic commands ###
