"""add elevation_profile to routes

Revision ID: 4a7b4678b2db
Revises: 9f7ea11b9bff
Create Date: 2026-09-18 14:40:26.667694

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a7b4678b2db"
down_revision: str | Sequence[str] | None = "9f7ea11b9bff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("routes", sa.Column("elevation_profile", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("routes", "elevation_profile")
    # ### end Alembic commands ###
