"""drop body_html from posts

Revision ID: 6b4e4b04943e
Revises: 8062f219765a
Create Date: 2026-09-03 16:45:32.106519

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6b4e4b04943e'
down_revision: str | Sequence[str] | None = '8062f219765a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
