"""add_body_blocks_column

Revision ID: 8062f219765a
Revises: 300e10b13ea8
Create Date: 2026-09-02 08:50:18.280983

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8062f219765a"
down_revision: str | Sequence[str] | None = "300e10b13ea8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing rows need a value before the NOT NULL constraint can apply —
    # server_default backfills them; the app-level default (Post.body_blocks
    # = list) is Python-side only and doesn't help existing rows.
    op.add_column(
        "posts",
        sa.Column(
            "body_blocks",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "body_blocks")
    # ### end Alembic commands ###
