"""add amenities_synced_at to routes

Revision ID: 9f7ea11b9bff
Revises: 2b3e2282a918
Create Date: 2026-09-10 17:21:01.267208

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f7ea11b9bff"
down_revision: str | Sequence[str] | None = "2b3e2282a918"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("routes", sa.Column("amenities_synced_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("routes", "amenities_synced_at")
    # ### end Alembic commands ###
